# This is used to configure the CAMEL loggers.
# Step handlers can be added by using a name that starts with 'step', pipeline handlers start with 'pipeline'.
# These handlers will create separate log files for each step / pipeline.
version: 1
formatters:
  basic:
    format: '%(process)6d - %(module)15s - %(levelname)7s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: basic
    stream: ext://sys.stdout

  main_debug:
    class: logging.FileHandler
    level: DEBUG
    formatter: basic
    filename: assembly_pipeline.log
    delay: True

  main_warning:
    class: logging.FileHandler
    level: WARNING
    formatter: basic
    filename: assembly_pipeline_warning.log
    delay: True

root:
  level: DEBUG
  handlers: [console, main_debug, main_warning]

disable_existing_loggers: False
